export { ReactComponent as IconAddToCart } from './icon-add-to-cart.svg'
export { ReactComponent as IconCarbonNeutral } from './icon-carbon-neutral.svg'
export { ReactComponent as IconDecrementQuantity } from './icon-decrement-quantity.svg'
export { ReactComponent as IconIncrementQuantity } from './icon-increment-quantity.svg'
export { ReactComponent as IconOrderConfirmed } from './icon-order-confirmed.svg'
export { ReactComponent as IconRemoveItem } from './icon-remove-item.svg'
export { ReactComponent as IconIllustrationEmptyCart } from './illustration-empty-cart.svg'